# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4643fa8113ea972be74e7c65839e909cecb2f64ffc8d015a56bd1a7e01be0003872b0d0173de4fa9e012cd9830359b934d04258118612dd71012bdda23a00976

test:
  secret_key_base: c8252286d2bedf211e7df619a2bc1350a70524da8011c1c5e9b87103a1c3738e16e2294447a67651f8d4e87316281d6c1a804b6136423d43179d184644a37604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
